// The app's own store: Postgres, at DATABASE_URL.
//
// One driver, `postgres`, because it runs the same under Node (`next dev`/`next
// start`, `node --test`) and Bun (the worker), and depends on nothing itself.
// Every query is a tagged template, so every value is a bound parameter.
//
// The connection is a parameter rather than something this file reads, so the
// tests can point it at a throwaway schema instead of the operator's data.
//
// Nobody signs in to audit. A user row exists only once someone continues with
// GitHub to link a repository, keyed by their GitHub id, and a browser holds
// only a random session id that points at it — tokens never leave the server.

import { createHash, randomBytes } from 'node:crypto';
import postgres from 'postgres';

import { siteKey } from './site-key.ts';

export { siteKey };

export type Db = postgres.Sql;

/** A repository linked to an audited site. */
export type Repo = {
  id: number;
  userId: number;
  /** The audited site this is linked to — a normalised `meta.origin`. */
  origin: string;
  owner: string;
  name: string;
  /** `null` means "whatever the repository calls its default branch", resolved
   *  at read time rather than frozen here — so a repo that renames `master` to
   *  `main` does not strand the link. */
  branch: string | null;
  /** The GitHub App installation that grants access to it. `null` on a link
   *  made before the app, which still reads — as the env token or anonymously —
   *  but cannot be written to. */
  installationId: number | null;
  createdAt: string;
};

// Timestamps stay ISO text, as they were in SQLite: they sort and compare as
// strings, and every caller already reads and writes them that way.
const SCHEMA = `
  CREATE TABLE IF NOT EXISTS users (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    github_id  BIGINT UNIQUE,
    created_at TEXT NOT NULL
  );

  -- The id is a hash of the cookie, so a copy of this table opens no browser's
  -- session.
  CREATE TABLE IF NOT EXISTS sessions (
    id         TEXT PRIMARY KEY,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TEXT NOT NULL
  );

  -- One crawl. Nobody owns it: the id is random, and whoever holds it can read it.
  CREATE TABLE IF NOT EXISTS audits (
    id          TEXT PRIMARY KEY,
    url         TEXT NOT NULL,
    params      TEXT NOT NULL,
    status      TEXT NOT NULL,
    result      TEXT,
    error       TEXT,
    created_at  TEXT NOT NULL,
    finished_at TEXT
  );

  CREATE TABLE IF NOT EXISTS repos (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    origin          TEXT NOT NULL,
    owner           TEXT NOT NULL,
    name            TEXT NOT NULL,
    branch          TEXT,
    installation_id BIGINT,
    created_at      TEXT NOT NULL,
    UNIQUE (user_id, origin)
  );

  -- A fix: the model's run against one linked repository, what it staged, and
  -- the pull request it became. The kind is 'ai' now; Phase B adds 'agent'.
  -- Queued by the web app, run by the worker (worker.ts); 'stop' is Stop
  -- pressed, which the worker reads.
  CREATE TABLE IF NOT EXISTS jobs (
    id          TEXT PRIMARY KEY,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    repo_id     INTEGER NOT NULL REFERENCES repos(id) ON DELETE CASCADE,
    audit_id    TEXT NOT NULL,
    kind        TEXT NOT NULL,
    status      TEXT NOT NULL,
    input       TEXT NOT NULL,
    output      TEXT,
    log         TEXT NOT NULL DEFAULT '[]',
    error       TEXT,
    tokens_in   INTEGER NOT NULL DEFAULT 0,
    tokens_out  INTEGER NOT NULL DEFAULT 0,
    pr          TEXT,
    stop        INTEGER NOT NULL DEFAULT 0,
    created_at  TEXT NOT NULL,
    finished_at TEXT
  );

  -- One fix per user queued or running, held by the store rather than by a
  -- check that two requests could both pass.
  CREATE UNIQUE INDEX IF NOT EXISTS jobs_one_active ON jobs (user_id) WHERE status IN ('queued', 'running');

  CREATE TABLE IF NOT EXISTS github_accounts (
    user_id       INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    login         TEXT NOT NULL,
    token         TEXT NOT NULL,
    refresh_token TEXT,
    expires_at    TEXT,
    created_at    TEXT NOT NULL
  );
`;

async function connect(url: string): Promise<Db> {
  // `undefined` becomes NULL, as SQLite took it; notices are the "already
  // exists, skipping" of every start.
  const db = postgres(url, { transform: { undefined: null }, onnotice: () => {} });
  // The web app and the worker both start by creating the schema, and two
  // `CREATE ... IF NOT EXISTS` at once can still collide — so one at a time.
  await db.begin(async (tx) => {
    await tx`SELECT pg_advisory_xact_lock(hashtext('seo-auditor schema'))`;
    await tx.unsafe(SCHEMA);
  });
  return db;
}

// One pool per URL, not per import, and on globalThis: `next dev` re-evaluates
// a module on every edit, and each evaluation opening its own pool is how a
// long dev session runs Postgres out of connections.
const g = globalThis as typeof globalThis & { __pools?: Map<string, Promise<Db>> };
const pools = (g.__pools ??= new Map());

/** Connect to (and on first call, create the tables in) the store at `url`. */
export function openDb(url = process.env.DATABASE_URL): Promise<Db> {
  if (!url) throw new Error('DATABASE_URL is not set: point it at a Postgres database, e.g. in .env.local.');
  let db = pools.get(url);
  if (!db) {
    db = connect(url);
    // A database that was down is asked again next time, not remembered as down.
    db.catch(() => pools.delete(url));
    pools.set(url, db);
  }
  return db;
}

const toRepo = (row: Record<string, unknown>): Repo => ({
  id: Number(row.id),
  userId: Number(row.user_id),
  origin: String(row.origin),
  owner: String(row.owner),
  name: String(row.name),
  branch: row.branch == null ? null : String(row.branch),
  installationId: row.installation_id == null ? null : Number(row.installation_id),
  createdAt: String(row.created_at),
});

/** The repository linked to `origin`, or `null` when there is none. */
export async function linkedRepo(db: Db, userId: number, origin: string): Promise<Repo | null> {
  const [row] = await db`SELECT * FROM repos WHERE user_id = ${userId} AND origin = ${siteKey(origin)}`;
  return row ? toRepo(row) : null;
}

export async function repoById(db: Db, id: number): Promise<Repo | null> {
  const [row] = await db`SELECT * FROM repos WHERE id = ${id}`;
  return row ? toRepo(row) : null;
}

/** Every link the user has, keyed by site — what the page hands the report so
 *  it can draw the panel without asking the server again. */
export async function linkedRepos(db: Db, userId: number): Promise<Record<string, Repo>> {
  const rows = (await db`SELECT * FROM repos WHERE user_id = ${userId}`).map(toRepo);
  return Object.fromEntries(rows.map((repo) => [repo.origin, repo]));
}

/** Link a repository to `origin`, replacing whatever was linked before.
 *
 *  An upsert rather than a delete-then-insert: one site has one repository, so
 *  re-linking is an edit of that fact, and a row id that survives the edit is
 *  one anything referencing it can keep holding. */
export async function linkRepo(
  db: Db,
  userId: number,
  origin: string,
  repo: { owner: string; name: string; branch?: string | null; installationId?: number | null },
): Promise<Repo> {
  const [row] = await db`
    INSERT INTO repos (user_id, origin, owner, name, branch, installation_id, created_at)
    VALUES (${userId}, ${siteKey(origin)}, ${repo.owner}, ${repo.name}, ${repo.branch ?? null},
            ${repo.installationId ?? null}, ${new Date().toISOString()})
    ON CONFLICT (user_id, origin)
    DO UPDATE SET owner = excluded.owner, name = excluded.name, branch = excluded.branch,
                  installation_id = excluded.installation_id
    RETURNING *`;
  return toRepo(row);
}

/** Forget the repository linked to `origin`. `false` when there was none. */
export async function unlinkRepo(db: Db, userId: number, origin: string): Promise<boolean> {
  return (await db`DELETE FROM repos WHERE user_id = ${userId} AND origin = ${siteKey(origin)}`).count > 0;
}

/** The GitHub account a user signed in with through the GitHub App.
 *
 *  `token` is the app's user token: it expires after eight hours, and
 *  `refreshToken` buys a new one — see `userToken()` in lib/git-state.ts.
 *
 *  ponytail: the tokens sit in plain text in the database — same trust as the
 *  database. Encrypt at rest the day this is hosted. */
export type GithubAccount = {
  login: string;
  token: string;
  refreshToken: string | null;
  /** ISO time the token stops working. `null` when the app does not expire them. */
  expiresAt: string | null;
};

export async function githubAccount(db: Db, userId: number): Promise<GithubAccount | null> {
  const [row] = await db`
    SELECT login, token, refresh_token, expires_at FROM github_accounts WHERE user_id = ${userId}`;
  if (!row) return null;
  return {
    login: String(row.login),
    token: String(row.token),
    refreshToken: row.refresh_token == null ? null : String(row.refresh_token),
    expiresAt: row.expires_at == null ? null : String(row.expires_at),
  };
}

export async function saveGithubAccount(db: Db, userId: number, account: GithubAccount): Promise<void> {
  await db`
    INSERT INTO github_accounts (user_id, login, token, refresh_token, expires_at, created_at)
    VALUES (${userId}, ${account.login}, ${account.token}, ${account.refreshToken}, ${account.expiresAt},
            ${new Date().toISOString()})
    ON CONFLICT (user_id) DO UPDATE SET login = excluded.login, token = excluded.token,
      refresh_token = excluded.refresh_token, expires_at = excluded.expires_at`;
}

export async function forgetGithubAccount(db: Db, userId: number): Promise<void> {
  await db`DELETE FROM github_accounts WHERE user_id = ${userId}`;
}

/** The user behind a GitHub account, made on their first sign-in. Keyed by
 *  GitHub's numeric id, which survives a renamed login. */
export async function userForGithub(db: Db, githubId: number, login: string): Promise<number> {
  const [row] = await db`
    INSERT INTO users (name, github_id, created_at) VALUES (${login}, ${githubId}, ${new Date().toISOString()})
    ON CONFLICT (github_id) DO UPDATE SET name = excluded.name
    RETURNING id`;
  return Number(row.id);
}

const SESSION_DAYS = 30;
const hashed = (token: string) => createHash('sha256').update(token).digest('hex');

/** A new session for `userId`. The return value goes in the browser's cookie
 *  and nowhere else — only its hash is kept. */
export async function createSession(db: Db, userId: number, now = Date.now()): Promise<string> {
  await db`DELETE FROM sessions WHERE expires_at < ${new Date(now).toISOString()}`;
  const token = randomBytes(32).toString('base64url');
  const expires = new Date(now + SESSION_DAYS * 86_400_000).toISOString();
  await db`INSERT INTO sessions (id, user_id, expires_at) VALUES (${hashed(token)}, ${userId}, ${expires})`;
  return token;
}

export const SESSION_COOKIE = 'sid';

/** The cookie that keeps a browser signed in. HttpOnly, so no script on the
 *  page can read it. Secure when the request arrived over HTTPS — asked of the
 *  request, not of NODE_ENV: `next start` on http://localhost is production,
 *  and Firefox silently drops a Secure cookie sent over plain http. */
export function sessionCookie(request: Request, token: string, maxAge = SESSION_DAYS * 86_400): string {
  const https =
    (request.headers.get('x-forwarded-proto') ?? new URL(request.url).protocol.replace(':', '')) === 'https';
  return `${SESSION_COOKIE}=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${https ? '; Secure' : ''}`;
}

/** Whose cookie this is, or `null` for a stranger, a forgery or an old one. */
export async function sessionUser(db: Db, token: string, now = Date.now()): Promise<number | null> {
  const [row] = await db`SELECT user_id, expires_at FROM sessions WHERE id = ${hashed(token)}`;
  if (!row || String(row.expires_at) < new Date(now).toISOString()) return null;
  return Number(row.user_id);
}

export async function endSession(db: Db, token: string): Promise<void> {
  await db`DELETE FROM sessions WHERE id = ${hashed(token)}`;
}

export type AuditStatus = 'queued' | 'running' | 'done' | 'failed';

export type Audit = {
  id: string;
  url: string;
  /** The query string the run was asked with — everything needed to start it. */
  params: string;
  status: AuditStatus;
  /** The finished report, as JSON. */
  result: string | null;
  error: string | null;
  createdAt: string;
};

/** How long a finished report stays fetchable. */
const KEEP_DAYS = 7;

export async function createAudit(
  db: Db,
  audit: { id: string; url: string; params: string },
  now = Date.now(),
): Promise<void> {
  await db`DELETE FROM audits WHERE created_at < ${new Date(now - KEEP_DAYS * 86_400_000).toISOString()}`;
  await db`
    INSERT INTO audits (id, url, params, status, created_at)
    VALUES (${audit.id}, ${audit.url}, ${audit.params}, 'queued', ${new Date(now).toISOString()})`;
}

export async function startAudit(db: Db, id: string): Promise<void> {
  await db`UPDATE audits SET status = 'running' WHERE id = ${id}`;
}

export async function finishAudit(db: Db, id: string, outcome: { result: string } | { error: string }): Promise<void> {
  await db`
    UPDATE audits SET status = ${'result' in outcome ? 'done' : 'failed'},
      result = ${'result' in outcome ? outcome.result : null},
      error = ${'error' in outcome ? outcome.error : null},
      finished_at = ${new Date().toISOString()}
    WHERE id = ${id}`;
}

export async function getAudit(db: Db, id: string): Promise<Audit | null> {
  const [row] = await db`SELECT * FROM audits WHERE id = ${id}`;
  if (!row) return null;
  return {
    id: String(row.id),
    url: String(row.url),
    params: String(row.params),
    status: String(row.status) as AuditStatus,
    result: row.result == null ? null : String(row.result),
    error: row.error == null ? null : String(row.error),
    createdAt: String(row.created_at),
  };
}

/** Runs a previous process started and never finished. The queue lives in
 *  memory, so after a restart nothing will ever pick these up again. */
export async function abandonAudits(db: Db, reason: string): Promise<number> {
  const done = await db`
    UPDATE audits SET status = 'failed', error = ${reason}, finished_at = ${new Date().toISOString()}
    WHERE status IN ('queued', 'running')`;
  return done.count;
}

export type JobStatus = 'queued' | 'running' | 'done' | 'failed';

/** What a fix asked for: the checks picked from one stored audit, and
 *  anything else in the user's own words — reported on as the id `request`. */
export type JobInput = { checks: string[]; request?: string };

/** What the model left staged, and what it says about each check. `before` is
 *  `null` for a file it created. */
export type JobOutput = {
  base: { branch: string; sha: string };
  summary: string;
  findings: { id: string; status: 'fixed' | 'skipped'; why: string }[];
  files: { path: string; before: string | null; after: string }[];
  /** Run in the sandbox after the model finished, when there is one. */
  checks?: Check[];
};

/** One command we ran on the changes. `before` is whether it passed without
 *  them, asked only when it failed with them. */
export type Check = { command: string; ok: boolean; before?: boolean; tail: string };

export type PullRequest = { number: number; url: string; branch: string; state: 'open' | 'closed' | 'merged' };

export type Job = {
  id: string;
  userId: number;
  repoId: number;
  auditId: string;
  status: JobStatus;
  input: JobInput;
  output: JobOutput | null;
  log: string[];
  error: string | null;
  tokens: { in: number; out: number };
  pr: PullRequest | null;
  createdAt: string;
};

const json = <T>(value: unknown, fallback: T): T => (value == null ? fallback : JSON.parse(String(value)));

const toJob = (row: Record<string, unknown>): Job => ({
  id: String(row.id),
  userId: Number(row.user_id),
  repoId: Number(row.repo_id),
  auditId: String(row.audit_id),
  status: String(row.status) as JobStatus,
  input: json(row.input, { checks: [] }),
  output: json(row.output, null),
  log: json(row.log, []),
  error: row.error == null ? null : String(row.error),
  tokens: { in: Number(row.tokens_in), out: Number(row.tokens_out) },
  pr: json(row.pr, null),
  createdAt: String(row.created_at),
});

export async function createJob(
  db: Db,
  job: { id: string; userId: number; repoId: number; auditId: string; input: JobInput },
): Promise<void> {
  await db`
    INSERT INTO jobs (id, user_id, repo_id, audit_id, kind, status, input, created_at)
    VALUES (${job.id}, ${job.userId}, ${job.repoId}, ${job.auditId}, 'ai', 'queued',
            ${JSON.stringify(job.input)}, ${new Date().toISOString()})`;
}

export async function getJob(db: Db, id: string): Promise<Job | null> {
  const [row] = await db`SELECT * FROM jobs WHERE id = ${id}`;
  return row ? toJob(row) : null;
}

/** A repository's fixes, newest first. */
export async function repoJobs(db: Db, repoId: number, limit = 20): Promise<Job[]> {
  return (await db`SELECT * FROM jobs WHERE repo_id = ${repoId} ORDER BY created_at DESC LIMIT ${limit}`).map(toJob);
}

/** The user's fix queued or running, if any — one at a time, because each
 *  spends the operator's model budget. */
export async function activeJob(db: Db, userId: number): Promise<Job | null> {
  const [row] = await db`SELECT * FROM jobs WHERE user_id = ${userId} AND status IN ('queued', 'running')`;
  return row ? toJob(row) : null;
}

/** The oldest queued job, now running — the worker's to run. SKIP LOCKED, so
 *  two workers asking at once get two different jobs, never the same one. */
export async function claimJob(db: Db): Promise<Job | null> {
  const [row] = await db`
    UPDATE jobs SET status = 'running'
    WHERE id = (SELECT id FROM jobs WHERE status = 'queued' ORDER BY created_at LIMIT 1 FOR UPDATE SKIP LOCKED)
    RETURNING *`;
  return row ? toJob(row) : null;
}

/** Stop pressed. A queued job ends here; a running one is flagged, and its
 *  worker aborts it within a second. Pressed again on one still running, its
 *  worker is gone or stuck, so it ends here too. */
export async function stopJob(db: Db, id: string, reason: string): Promise<void> {
  await db`
    UPDATE jobs SET status = 'failed', error = ${reason}, finished_at = ${new Date().toISOString()}
    WHERE id = ${id} AND (status = 'queued' OR (status = 'running' AND stop = 1))`;
  await db`UPDATE jobs SET stop = 1 WHERE id = ${id} AND status = 'running'`;
}

/** Running jobs someone pressed Stop on. */
export const stopsAsked = async (db: Db): Promise<string[]> =>
  (await db`SELECT id FROM jobs WHERE status = 'running' AND stop = 1`).map((row) => String(row.id));

export async function logJob(db: Db, id: string, log: string[], tokens: { in: number; out: number }): Promise<void> {
  await db`
    UPDATE jobs SET log = ${JSON.stringify(log)}, tokens_in = ${tokens.in}, tokens_out = ${tokens.out}
    WHERE id = ${id}`;
}

/** `error` beside an `output` is a run that finished whose pull request did
 *  not open — the changes are kept, so it can be tried again. */
export async function finishJob(
  db: Db,
  id: string,
  outcome: { output: JobOutput; error?: string } | { error: string },
): Promise<void> {
  await db`
    UPDATE jobs SET status = ${'output' in outcome ? 'done' : 'failed'},
      output = ${'output' in outcome ? JSON.stringify(outcome.output) : null},
      error = ${outcome.error ?? null},
      finished_at = ${new Date().toISOString()}
    WHERE id = ${id}`;
}

export async function setJobPr(db: Db, id: string, pr: PullRequest): Promise<void> {
  await db`UPDATE jobs SET pr = ${JSON.stringify(pr)} WHERE id = ${id}`;
}

/** Fixes a previous worker was running. The run lived in its memory; queued
 *  ones wait for the next. */
export async function abandonJobs(db: Db, reason: string): Promise<number> {
  const done = await db`
    UPDATE jobs SET status = 'failed', error = ${reason}, finished_at = ${new Date().toISOString()}
    WHERE status = 'running'`;
  return done.count;
}
